import React, { Component } from 'react';
import { loremIpsum } from "lorem-ipsum";
import '../../../../node_modules/bootstrap/dist/css/bootstrap.css';
import './solar.css';
import '../../../../node_modules/font-awesome/css/font-awesome.min.css';
import '../../navbar/navbar';
import Navbar from '../../navbar/navbar';

const Solar = props => {
    return (
      <div>
        
          <div className="sol-top">
            <div className="sol-nave">
              <Navbar></Navbar>
            </div>
            <div className="sol-frnt-image">
              <img className="sol-top-img" src="../solar4.jpg"></img>
            </div>
            <div className="sol-resr-box">
              <div className="sol-write">
                  <h2>Solar Energy</h2>
                  <p>
                  Solar power is energy from the sun that is converted into thermal or electrical energy. Solar energy is the cleanest and most abundant renewable energy source available, and the U.S. has some of the richest solar resources in the world. Solar technologies can harness this energy for a variety of uses, including generating electricity, providing light or a comfortable interior environment, and heating water for domestic, commercial, or industrial use.
                  </p>
                  </div>
            </div>
            </div>

            <div className="sol-new-resr-box">
              <div className="sol-new-write">
                  <h2>How It Works</h2>
                  <p>
                  There are three main ways to harness solar energy: photovoltaics, solar heating & cooling, and concentrating solar power. Photovoltaics generate electricity directly from sunlight via an electronic process and can be used to power anything from small electronics such as calculators and road signs up to homes and large commercial businesses. Solar heating & cooling (SHC) and concentrating solar power (CSP) applications both use the heat generated by the sun to provide space or water heating in the case of SHC systems, or to run traditional electricity-generating turbines in the case of CSP power plants.
                  </p>
                  <p>
                  The sun does more than for our planet than just provide light during the daytime – each particle of sunlight (called a photon) that reaches Earth contains energy that fuels our planet. Solar energy is the ultimate source responsible for all of our weather systems and energy sources on Earth, and enough solar radiation hits the surface of the planet each hour to theoretically fill our global energy needs for nearly an entire year.

                  Where does all of this energy come from? Our sun, like any star in the galaxy, is like a massive nuclear reactor. Deep in the Sun’s core, nuclear fusion reactions produce massive amounts of energy that radiates outward from the Sun’s surface and into space in the form of light and heat.

                  Solar power can be harnessed and converted to usable energy using photovoltaics or solar thermal collectors. Although solar energy only accounts for a small amount of overall global energy use, the falling cost of installing solar panels means that more and more people in more places can take advantage of solar energy. Solar is a clean, renewable energy resource, and figures to play an important part in the global energy future.
                  </p>

                  <h2>What Does It Costs?</h2>
                  <p>
                    <ul>
                      <li>High initial costs for material and installation and long ROI (however, with the reduction in cost of solar over the last 10 years, solar is becoming more cost feasible every day)</li>
                      <li>Cloudy days do not produce as much energy</li>
                      <li>Solar panels are not being massed produced due to lack of material and technology to lower the cost enough to be more affordable (this is starting to change)</li>
                      <li>No solar power at night so there is a need for a large battery bank</li>
                      <li>Needs lots of space as efficiency is not 100% yet</li>
                    </ul>
                  </p>
                  </div>
            </div>

            <div className="sol-rect">
              <div className="row">
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                    <p>Solar</p> 
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Wind</p> 
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Hydro</p>  
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Geothermal</p> 
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Timbers</p> 
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                    <p>Biomass</p>
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Radiant</p> 
                  </div>
                </div>
                <div className="col-md-3 col-sm-4 sol-cl">
                  <div className="sol-sqr">
                  <p>Tidal</p> 
                  </div>
                </div>
              </div>
            </div>

         

</div>        
    )
  }

export default Solar;

